# Generated by Django 4.1.2 on 2023-05-20 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="image_namge",
            new_name="image_name",
        ),
    ]
